kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cfs-sc
provisioner: csi-cfsplugin
reclaimPolicy: Retain
parameters:
  masterAddr: 172.20.240.95:80;172.20.240.94:80;172.20.240.67:80
  volName: cfsvol-csi 
