kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cfs-sc
provisioner: chubaofs-csi-v1.0.0
reclaimPolicy: Delete
parameters:
  #fsType, only support 'chubaofs' for now
  fsType: chubaofs
