kind: Deployment
apiVersion: apps/v1
metadata:
  name: cfs-csi-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app: cfs-csi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: cfs-csi-controller
    spec:
      serviceAccount: cfs-csi-service-account
      nodeSelector:
        csi.chubaofs.com/controller: enabled
      containers:
        - name: external-provisioner
          image: quay.io/k8scsi/csi-provisioner:v0.4.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - --v=5
            - --provisioner=csi.chubaofs.com
            - --csi-address=$(ADDRESS)
            - --kubeconfig=/etc/kubernetes/config
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADDRESS
              value: /csi/csi.sock
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          # limits:
          #   cpu: 500m
          #   memory: 512Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - name: kube-config
              mountPath: /etc/kubernetes
        - name: external-attacher
          image: quay.io/k8scsi/csi-attacher:v0.4.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
            - --kubeconfig=/etc/kubernetes/config
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADDRESS
              value: /csi/csi.sock
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - name: kube-config
              mountPath: /etc/kubernetes
        - name: cfs-driver
          image: chubaofs/cfs-csi-driver:2.1.3
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /bin/tini
            - "--"
            - bash
            - "-c"
            - |-
              set -e
              su -p -s /bin/bash -c "/cfs/bin/start.sh &"
              su -p -s /bin/bash -c "sleep 9999999d"
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: KUBE_CONFIG
              value: /etc/kubernetes/config
            - name: LOG_LEVEL
              value: "5"
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: DRIVER_NAME
              value: csi.chubaofs.com
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - name: kube-config
              mountPath: /etc/kubernetes
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi.chubaofs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
          name: mountpoint-dir
        - configMap:
            name: csi-kube-config
          name: kube-config
