kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cfs-sc
  namespace: default
provisioner: csi.chubaofs.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  # Resource manager IP address or URL
  masterAddr: "master-service.chubaofs.svc.cluster.local:17010"
  # Owner name as authentication
  owner: "csiuser"
