#Deploy controller server and node server in the same pod, not suggested
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cfs-driver
  name: cfscsi-pod
  namespace: chubaofs
spec:
  serviceAccount: csi-service-account
  nodeName: 10.206.7.17
  containers:
  - name: external-provisioner
    args:
    - --v=5
    - --provisioner=chubaofs-csi-v1.0.0
    - --csi-address=/csi/csi.sock
    - --kubeconfig=/etc/k8s/kubecfg
    image: quay.io/k8scsi/csi-provisioner:v1.0.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /csi
      name: socket-dir
    - name: kubecfg
      mountPath: /etc/k8s

  - name: driver-registrar
    args:
      - --v=5
      - --csi-address=$(ADDRESS)
      - --kubeconfig=/etc/k8s/kubecfg
      - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
    lifecycle:
      preStop:
      exec:
      command: ["/bin/sh", "-c", "rm -rf /registration/chubaofs-csi-v1.0.0-reg.sock /csi/csi.sock"]
    env:
      - name: KUBE_NODE_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      - name: ADDRESS
        value: /csi/csi.sock
      - name: DRIVER_REG_SOCK_PATH
        value: /export/kubelet/plugins/chubaofs-csi-v1.0.0/csi.sock
    image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /csi
      name: socket-dir
    - mountPath: /registration
      name: registration-dir
    - name: kubecfg
      mountPath: /etc/k8s

  - name: external-attacher
    args:
    - --v=5
    - --csi-address=$(ADDRESS)
    - --kubeconfig=/etc/k8s/kubecfg
    env:
    - name: ADDRESS
      value: /csi/csi.sock
    image: quay.io/k8scsi/csi-attacher:v1.0.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /csi
      name: socket-dir
    - name: kubecfg
      mountPath: /etc/k8s

  - name: cfs-driver
    args:
    - --v=5
    - --endpoint=$(CSI_ENDPOINT)
    - --nodeid=$(KUBE_NODE_NAME)
    - --masterAddress=$(MASTER_ADDRESS)
    - --drivername=$(DRIVER_NAME)
    env:
    - name: CSI_ENDPOINT
      value: unix:///csi/csi.sock
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: MASTER_ADDRESS
      value: cfs.jd.com
    - name: DRIVER_NAME
      value: chubaofs-csi-v1.0.0
    image: quay.io/k8scsi/cfscsi:v1.0.0
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /csi
      name: socket-dir
    - mountPath: /export/kubelet/pods
      mountPropagation: Bidirectional
      name: mountpoint-dir

  volumes:
  - hostPath:
      path: /export/kubelet/plugins/chubaofs-csi-v1.0.0
      type: DirectoryOrCreate
    name: socket-dir
  - hostPath:
      path: /export/kubelet/plugins_registry/
      type: DirectoryOrCreate
    name: registration-dir
  - hostPath:
      path: /export/kubelet/pods/
      type: DirectoryOrCreate
    name: mountpoint-dir
  - configMap:
      name: kubecfg
    name: kubecfg
